on:
  push:
    branches: master

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.0.4

      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get install --yes libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
      
      - name: Install XQuartz
        if: runner.os == 'macOS'
        run: brew cask install xquartz

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ubuntu-r-4.0-4-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ubuntu-r-4.0-4-

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          install.packages('pkgdown')
          install.packages('devtools')
          install.packages("BiocManager")
          BiocManager::install("IRanges")
          remotes::install_dev("dplyr")
          devtools::install_github("YuLab-SMU/ggtree")
          install.packages("Hmisc")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Session Info
        run: |
          library(tidyverse)
          library(IRanges)
          library(gggenomes)
          print(sessionInfo())
        shell: Rscript {0}

#      - name: Setup upterm session
#        uses: lhotari/action-upterm@v1

      - name: Configure git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy package
        run: pkgdown::deploy_to_branch(new_process = FALSE, lazy=FALSE)
        shell: Rscript {0}
